import = [
   "~/.config/alacritty/themes/dracula.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 11
padding.y = 11

decorations = "None"

opacity = 1.0
blur = true

option_as_alt = "Both"
startup_mode = "Maximized"
title = "Let's Innovate"

[font]
normal.family = "JetBrainsMono NF"
offset.y = 4 # for line spacing default is 0

size = 16
