require("sar.core.statuscolumn")
require("sar.core.options")
require("sar.core.keymaps")
require("sar.core.xcode-dark")
require("sar.core.autocmds")
require("sar.core.folding")
require("sar.core.diagnostics")
